alias r='bin/rails'
alias rc='bin/rails c'
alias rs='bin/rails s'
alias killrails='kill -9 $(cat ./tmp/pids/server.pid)'
alias u='ru && nu'
alias wds='bin/webpack-dev-server'
alias ff='bundle exec rspec --fail-fast'
